import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Particles } from "@/components/ui/particles";
import { ThemeProvider } from "@/components/theme-provider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Escolha os pesos que você precisar
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased h-full`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="relative h-full">
            {children}
            <Particles
              className="absolute inset-0 z-0"
              quantity={100}
              ease={80}
              refresh
            />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
